Users/urls.py
from django.urls import path
from .views import create_user, main_page, logIn, create_post, articles, \
    logOut, filter_categories, filter_place, user_page, ChangePasswordView, UpdatePostView, user_posts
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', create_user, name='registiration-page'),
    path('edit-user', user_page, name='edit-user'),
    path('edit-user/change-password', ChangePasswordView.as_view(template_name='profilePage/password-change.html'), name='password-page'),
    path('kirish', logIn, name='login-page'),
    path('create/post', create_post, name='create-post'),
    path('logout-user', logOut, name='logout'),
    path('category/<slug:slug>', filter_categories, name='filter-categories'),
    path('place/<slug:slug>', filter_place, name='filter-places'),
    path('article/<slug:slug>', articles, name='article-page'),
    path('article/edit/<slug:slug>', UpdatePostView.as_view(), name='article-edit'),
    path('bosh-sahifa/', main_page, name='main-page'),
    path('my-posts/', user_posts, name='user-page'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogWebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('_admin/', admin.site.urls),
    path('', include('Users.urls')),
]

Users/models.py
from django.db import models
from django.contrib.auth import settings
from django.contrib.auth.models import AbstractUser
from datetime import datetime
from autoslug import AutoSlugField

class CustomUser(AbstractUser):
    address = models.CharField(max_length=40)
    phone_number = models.CharField(max_length=14)


class CategoryClass(models.Model):
    title = models.CharField(max_length=100)
    slug = AutoSlugField(populate_from='title', unique=True)

    def __str__(self):
        return self.title


class Place(models.Model):
    title = models.CharField(max_length=100)
    slug = AutoSlugField(populate_from='title', unique=True)

    def __str__(self):
        return self.title


class Post(models.Model):
    User = settings.AUTH_USER_MODEL
    title = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=User)
    slug = AutoSlugField(populate_from='title', unique=True)
    content = models.TextField()
    description = models.TextField(blank=True, null=True)
    categories = models.ManyToManyField(to='CategoryClass', related_name='Categories', null=True, blank=True)
    places = models.ManyToManyField(to='Place', related_name='Places', null=True, blank=True)
    image = models.ImageField(upload_to="images/")
    published_at = models.DateTimeField(default=datetime.now)

    class Meta:
        ordering = ('-id',)

    def __str__(self):
        return self.title

templates/profilePage/cabinet.html
{% extends 'blocks/base.html' %}

{% if user.is_authenticated %}
    {% block title %} Welcome {{ user.username }}! {% endblock %}
    {% block content %}
        <div class="d-flex">
        <div class="col-4 col-lg-4"></div>
        <div class="col-4 col-lg-4 pt-lg-5">
            <form action="" method="post">
                {% csrf_token %}
                <label for="user_id"></label> <input type="text" name="user_id" class="form-control"
                                                                     maxlength="" autofocus="" required=""
                                                                     value="{{ user.id }}"
                                                                     id="user_id" hidden>
                <p><label for="id_username">Username:</label> <input type="text" name="username" class="form-control"
                                                                     maxlength="150" autofocus="" required=""
                                                                     value="{{ user.username }}"
                                                                     id="id_username"></p>
                <p><label for="id_address">Address:</label> <input type="text" name="address" class="form-control"
                                                                   maxlength="40" required="" id="id_address"
                                                                   value="{{ user.address }}"></p>
                <p><label for="id_phone_number">Phone number:</label> <input type="text" name="phone_number"
                                                                             class="form-control" maxlength="14"
                                                                             required="" value="{{ user.phone_number }}"
                                                                             id="id_phone_number"></p>
                <a class="d-block" href="{% url 'password-page' %}">Change Password</a>
                <button type="submit" class="btn btn-primary btn-lg w-100" data-toggle="button" aria-pressed="false">
                    Save
                </button>
            </form>
        </div>
        <div class="col-4 col-lg-4"></div>
        </div>

    {% endblock %}{% endif %}

templates/profilePage/createPost.html
{% extends 'blocks/base.html' %}
{% block title %} Post Yaratish {% endblock %}
{% block content %}
    <div class="form-group col-lg-6 p-5">
        <a href="{% url 'main-page' %}">< Bosh Sahifa</a>
        <h2>Post Yaratish</h2>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <button type="submit" class="btn btn-secondary">Yaratish</button>
        </form>
    </div>
    {% load static %}
    <script src="{% static 'assets/js/jquery-3.3.1.slim.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/js/popper.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}" type="text/javascript"></script>
{% endblock %}

templates/profilePage/main.html
{% extends 'blocks/base.html' %}


{% if user.is_authenticated %}
    {% block title %} Welcome {{ user.username }}! {% endblock %}
    {% block content %}
        <div class="row">
            {% if post %}
                {% for info in post %}
                    <div class="col-lg-6 p-4" style="border: 1px solid #000000; height: 420px">
                        {% if info.image %}
                            <img src="{{ info.image.url }}" alt="{{ info.title }}" class="w-100 h-50" style="
object-fit: cover;">{% endif %}
                        <p class="mb-0 pt-2">{{ info.published_at.time }} / {{ info.published_at.date }}</p>
                        <h3><a href="/article/{{ info.slug }}" title="{{ info.title }}">{{ info.title }}</a></h3>
                        <p>{{ info.description }}</p>
                        <a href="/article/{{ info.slug }}">Batafsil</a>
                    </div>
                {% endfor %}
            {% endif %}

        </div>
        {% load static %}
        <script src="{% static 'assets/js/jquery-3.3.1.slim.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'assets/js/popper.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'assets/js/bootstrap.min.js' %}" type="text/javascript"></script>
    {% endblock %}
{% endif %}

templates/profilePage/password-change.html
{% extends 'blocks/base.html' %}
{% block title %} Change Password! {% endblock %}
{% block content %}
    <div class="d-flex">
        <div class="col-4 col-lg-4"></div>
        <div class="col-4 col-lg-4 pt-lg-5">
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary btn-lg w-100" data-toggle="button" aria-pressed="false">
                    Change Password
                </button>
                <br><br>
                <ul>
                    <li>Your password can’t be too similar to your other personal information.</li>
                    <li>Your password must contain at least 8 characters.</li>
                    <li>Your password can’t be a commonly used password.</li>
                    <li>Your password can’t be entirely numeric.</li>
                </ul>
            </form>
        </div>
        <div class="col-4 col-lg-4"></div>
    </div>


{% endblock %}

templates/profilePage/single.html
{% extends 'blocks/base.html' %}
{% if article %}
    {% block title %} {{ article.title }} {% endblock %}
    {% block content %}
        <div class="p-4">
            <a href="{% url 'main-page' %}">< Bosh Sahifa</a>
            {% if article.image %}
                <img src="{{ article.image.url }}" alt="{{ article.title }}" style="margin: 0 auto; border: 1px solid #0c83e2;
    width: 100%;
    height: 400px;
    object-fit: cover;">
            {% endif %}
            <p class="mb-0 pt-2">{{ article.published_at.time }} / {{ article.published_at.date }}</p>
            <h1>{{ article.title }}</h1>
            <p>{{ article.content }}</p>
        </div>
        {% load static %}
        <script src="{% static 'assets/js/jquery-3.3.1.slim.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'assets/js/popper.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'assets/js/bootstrap.min.js' %}" type="text/javascript"></script>
    {% endblock %}
{% endif %}

templates/profilePage/update_post.html
{% extends 'blocks/base.html' %}
{% block title %} Edit Post {% endblock %}
{% block content %}
<div class="form-group col-lg-6 p-5" >
    <a href="{% url 'main-page' %}">< Bosh Sahifa</a>
    <h2>Edit Post</h2>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <button type="submit" class="btn btn-secondary">Edit</button>
    </form>
</div>
{% endblock %}

templates/profilePage/user_page.html
{% extends 'blocks/base.html' %}
{% block title %} All Posts {% endblock %}
{% block content %}
<div class="form-group col-lg-12 p-5" >
    <a href="{% url 'main-page' %}">< Bosh Sahifa</a>
    <h2>All Posts</h2>
        <div class="row">
            {% if post %}
                {% for info in post %}
                    <div class="col-lg-3 p-4" style="border: 1px solid #000000; height: 420px">
                        {% if info.image %}
                            <img src="{{ info.image.url }}" alt="{{ info.title }}" class="w-100 h-50" style="
object-fit: cover;">{% endif %}
                        <p class="mb-0 pt-2">{{ info.published_at.time }} / {{ info.published_at.date }}</p>
                        <h3><a href="/article/{{ info.slug }}" title="{{ info.title }}">{{ info.title }}</a></h3>
                        <p>{{ info.description }}</p>
                        <a href="/article/edit/{{ info.slug }}">Edit</a>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
        {% load static %}
        <script src="{% static 'assets/js/jquery-3.3.1.slim.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'assets/js/popper.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'assets/js/bootstrap.min.js' %}" type="text/javascript"></script>
</div>
{% endblock %}